language: go
go:
- 1.4.2
addons:
  apt:
    packages:
    - time
sudo: false
env: 'PD_PROJECT=cronner GOARCH=amd64 GOOS=linux PD_BUILD_NAME="$PD_PROJECT-$GOOS-$GOARCH-tbn$TRAVIS_BUILD_NUMBER-${TRAVIS_COMMIT:0:8}"'
script: go test -v ./... -check.vv
before_deploy:
- mkdir build
- mkdir $PD_BUILD_NAME
- go build -o $PD_BUILD_NAME/$PD_PROJECT
- tar -czf build/$PD_BUILD_NAME.tar.gz $PD_BUILD_NAME/
deploy:
  provider: releases
  skip_cleanup: true
  file: build/$PD_BUILD_NAME.tar.gz
  on:
    repo: PagerDuty/cronner
    tags: true
  api_key:
    secure: HNF+SPbS4QVhXG7+lf4ysphXHOJ04zy1yZrmAFWAprFbbDo6IlVwfdGXRB61d1yqG4O4BR3VhhbVmgqvaTMbXbDf3TycRC8Xt84c6BPkAecnDYMb/NNDdOzDagad8FJiWy13JwBJYzMF4B20tzbQcRtQSqxsjMqeyMuQDwjtWeU=
